#!/usr/bin/env -S nft -I /usr/share/nftables -f

# Flush all existing rules and tables
include "flush-drop.nft"
#include "flush-accept.nft"

# Enable local communication
include "loopback.nft"

# Include known ethernet addresses
include "ethers.nft"

# Configure ICMP / ICMPv6
include "icmp.nft"

# Local clients
include "client.nft"

# Local server services
include "server.nft"

#
# Special rules
#
include "special/nat-wlan0-eth0-masq.nft"

# Log dropped packets
#include "log-dropped.nft"

